spring.application.name=dev-diaries

spring.config.import=optional:dotenv
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
app.security.secret-key=${SECRET-KEY}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.mvc.problemdetails.enabled=true
spring.web.error.include-stacktrace=always
spring.web.error.include-exception=true
spring.web.error.include-message=always

logging.level.org.springframework.security=trace


